shopify_defined_subheaders = [
	'order_number',
	'updated_at',
	'contact_email',
	'total_line_items_price',
	'discount_codes.code',
	'discount_codes.amount',
	'current_subtotal_price',
	'total_shipping_price_set.shop_money.amount',
	'total_tip_received',
	'current_total_price',
	'current_total_tax',
	'landing_site',
	'name',
	'note',
	'payment_gateway_names',
	'tags'
	# 'confirmation_number',
	# 'total_weight',
	# 'customer.id',
	# 'customer.email',
	# 'customer.first_name',
	# 'customer.last_name',
	# 'line_items.id',
	# 'line_items.name',
	# 'line_items.price',
	# 'fulfillments.id',
	# 'fulfillments.created_at',
]