#todo split into different config text files
shopify_defined_subheaders_orders = [
	'order_number',
	'updated_at',
	'contact_email',
	'total_line_items_price',
	'discount_codes.code',
	'discount_codes.amount',
	'current_subtotal_price',
	'total_shipping_price_set.shop_money.amount',
	'total_tip_received',
	'current_total_price',
	'current_total_tax',
	'landing_site',
	'name',
	'note',
	'payment_gateway_names',
	'tags'
	# 'confirmation_number',
	# 'total_weight',
	# 'customer.id',
	# 'customer.email',
	# 'customer.first_name',
	# 'customer.last_name',
	# 'line_items.id',
	# 'line_items.name',
	# 'line_items.price',
	# 'fulfillments.id',
	# 'fulfillments.created_at',
]

shopify_defined_subheaders_customers = [
	'id',
	'email',
	'created_at',
	# 'updated_at',
	'first_name',
	'last_name',
	'orders_count',
	# 'state',
	'total_spent',
	'last_order_id',
	'note',
	# 'verified_email',
	# 'multipass_identifier',
	# 'tax_exempt',
	'tags',
	'last_order_name',
	# 'currency',
	# 'phone',
	# 'addresses.id',
	# 'addresses.customer_id',
	# 'addresses.first_name',
	# 'addresses.last_name',
	# 'addresses.company',
	# 'addresses.address1',
	# 'addresses.address2',
	'addresses.city',
	# 'addresses.province',
	# 'addresses.country',
	# 'addresses.zip',
	# 'addresses.phone',
	# 'addresses.name',
	# 'addresses.province_code',
	# 'addresses.country_code',
	'addresses.country_name',
	# 'addresses.default',
	# 'tax_exemptions',
	'email_marketing_consent.state',
	# 'email_marketing_consent.opt_in_level',
	# 'email_marketing_consent.consent_updated_at',
	# 'sms_marketing_consent.state',
	# 'sms_marketing_consent.opt_in_level',
	# 'sms_marketing_consent.consent_updated_at',
	# 'sms_marketing_consent.consent_collected_from',
	# 'admin_graphql_api_id',
	# 'default_address.id',
	# 'default_address.customer_id',
	# 'default_address.first_name',
	# 'default_address.last_name',
	# 'default_address.company',
	# 'default_address.address1',
	# 'default_address.address2',
	# 'default_address.city',
	# 'default_address.province',
	# 'default_address.country',
	# 'default_address.zip',
	# 'default_address.phone',
	# 'default_address.name',
	# 'default_address.province_code',
	# 'default_address.country_code',
	# 'default_address.country_name',
	# 'default_address.default'
]


starshipit_defined_subheaders = [
	'order_id',
	'order_date',
	'shipped_date',
	'order_number',
	# 'status',
	'order_type',
	'reference',
	'carrier',
	'carrier_name',
	'carrier_service_code',
	'shipping_method',
	# 'signature_required',
	# 'dangerous_goods',
	# 'currency',
	# 'sender_details.name',
	# 'sender_details.email',
	# 'sender_details.phone',
	# 'sender_details.street',
	# 'sender_details.suburb',
	# 'sender_details.city',
	# 'sender_details.state',
	# 'sender_details.post_code',
	# 'sender_details.country',
	# 'destination.name',
	# 'destination.email',
	# 'destination.street',
	# 'destination.suburb',
	# 'destination.city',
	# 'destination.state',
	'destination.post_code',
	'destination.country',
	# 'items.description',
	# 'items.sku',
	# 'items.country_of_origin',
	'items.quantity',
	'items.weight',
	# 'items.value',
	'packages.name',
	'packages.weight',
	# 'packages.height',
	# 'packages.width',
	# 'packages.length',
	'packages.packaging_type',
	# 'metadatas.metafield_key',
	# 'metadatas.value',
	'declared_value',
	# 'archived',
	# 'manifest_number',
	# 'address_validation',
	# 'create_return',
	# 'dtp',
	# 'add_insurance',
	# 'insurance_value',
	# 'plt',
	# 'type',
	# 'platform',
]

# https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema
#limit of 10
google_defined_headers_metrics = [
	"sessions",
	# "addToCarts",
	# "checkouts",
	# "transactions",
	# "averagePurchaseRevenue",
	# "bounceRate",
	# "eventsPerSession",
	# "advertiserAdCostPerClick",
	# "advertiserAdCostPerConversion",
	# "engagedSessions",
	# "firstTimePurchasers",
	# "grossPurchaseRevenue",
	# "itemDiscountAmount",
	# "itemsViewed",
	# "itemsPurchased",
	# "organicGoogleSearchAveragePosition",
	# "organicGoogleSearchClicks",
	# "promotionClicks",
	# "transactionsPerPurchaser",
	# "userEngagementDuration"
]

# https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema
# limit of 9
google_defined_headers_dimensions = [
	# "date",
	"dateHour",
	# "dateHourMinute",
	# "dayOfWeekName",
	# "landingPage",
	# "campaignName",
	# "browser",
	# "firstSessionDate",
	# "sessionSource",
	# "userAgeBracket",
	# "userGender"
]

cin7_defined_subheaders = [
	'id',
	'status',
	'createdDate',
	'modifiedDate',
	# 'styleCode',
	'name',
	# 'tags',
	'brand',
	'category',
	'subCategory',
	# 'channels',
	'weight',
	# 'height',
	# 'width',
	# 'length',
	# 'volume',
	'stockControl',
	'orderType',
	'productType',
	# 'optionLabel1',
	'salesAccount',
	# 'productOptions.id',
	'productOptions.status',
	'productOptions.productId',
	# 'productOptions.code',
	# 'productOptions.barcode',
	# 'productOptions.option1',
	'productOptions.optionWeight',
	'productOptions.retailPrice',
	# 'productOptions.wholesalePrice',
	# 'productOptions.vipPrice',
	# 'productOptions.specialPrice',
	'productOptions.stockAvailable',
	'productOptions.stockOnHand',
	# 'productOptions.priceColumns.retailNZD',
	# 'productOptions.priceColumns.vipnzd',
	# 'productOptions.priceColumns.wholesaleNZD',
	# 'productOptions.priceColumns.priceAUD',
	# 'productOptions.priceColumns.priceUSD',
	'productOptions.priceColumns.costNZD',
	# 'productOptions.priceColumns.costUSD',
	# 'productOptions.priceColumns.costAUD',
	# 'productOptions.priceColumns.specialPrice'
]

facebook_insights_headers = [
	# 'page_total_actions',
	# 'page_engaged_users',
	# 'page_impressions_organic_v2',
	'page_fan_removes_unique',
	# 'page_fans_by_like_source'
	# 'page_impressions',
	# 'page_views_total',
	# 'page_fan_adds_unique'

	# "accounts_engaged",
	# "total_interactions",
	# "likes",
	# "comments",
	# "shares",
	# "saves",
	# "replies",
	# "engaged_audience_demographics",
	# "reached_audience_demographics",
	# "follower_demographics",
	# "follows_and_unfollows",
	# "profile_links_taps"
]

instagram_insights_headers = [
	"impressions",
	# "reach",
	# "follower_count",
	# "email_contacts",
	# "phone_call_clicks",
	# "text_message_clicks",
	# "get_directions_clicks",
	# "website_clicks",
	# "profile_views",
	# "audience_gender_age",
	# "audience_locale",
	# "audience_country",
	# "audience_city",
	# "online_followers",
	# "accounts_engaged",
	# "total_interactions",
	# "likes",
	# "comments",
	# "shares",
	# "saves",
	# "replies",
	# "engaged_audience_demographics",
	# "reached_audience_demographics",
	# "follower_demographics",
	# "follows_and_unfollows",
	# "profile_links_taps"
]